name: Build and Release Chitti

on:
  push:
    tags:
      - 'v*'  # e.g., v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore Chitti/Chitti.csproj

      - name: Publish using .pubxml
        run: dotnet publish Chitti/Chitti.csproj -p:PublishProfile=FolderProfile1

      - name: Upload EXE to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Chitti Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: Chitti/bin/Release/net7.0-windows/win-x86/publish/Chitti.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
